# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Leonard/Documents/Programming/C++/Lotus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Leonard/Documents/Programming/C++/Lotus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Leonard/Documents/Programming/C++/Lotus/CMakeFiles /Users/Leonard/Documents/Programming/C++/Lotus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Leonard/Documents/Programming/C++/Lotus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lotus

# Build rule for target.
Lotus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lotus
.PHONY : Lotus

# fast build rule for target.
Lotus/fast:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/build
.PHONY : Lotus/fast

src/graphics/buffers/lotus_buffer.o: src/graphics/buffers/lotus_buffer.cpp.o
.PHONY : src/graphics/buffers/lotus_buffer.o

# target to build an object file
src/graphics/buffers/lotus_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_buffer.cpp.o
.PHONY : src/graphics/buffers/lotus_buffer.cpp.o

src/graphics/buffers/lotus_buffer.i: src/graphics/buffers/lotus_buffer.cpp.i
.PHONY : src/graphics/buffers/lotus_buffer.i

# target to preprocess a source file
src/graphics/buffers/lotus_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_buffer.cpp.i
.PHONY : src/graphics/buffers/lotus_buffer.cpp.i

src/graphics/buffers/lotus_buffer.s: src/graphics/buffers/lotus_buffer.cpp.s
.PHONY : src/graphics/buffers/lotus_buffer.s

# target to generate assembly for a file
src/graphics/buffers/lotus_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_buffer.cpp.s
.PHONY : src/graphics/buffers/lotus_buffer.cpp.s

src/graphics/buffers/lotus_indexbuffer.o: src/graphics/buffers/lotus_indexbuffer.cpp.o
.PHONY : src/graphics/buffers/lotus_indexbuffer.o

# target to build an object file
src/graphics/buffers/lotus_indexbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_indexbuffer.cpp.o
.PHONY : src/graphics/buffers/lotus_indexbuffer.cpp.o

src/graphics/buffers/lotus_indexbuffer.i: src/graphics/buffers/lotus_indexbuffer.cpp.i
.PHONY : src/graphics/buffers/lotus_indexbuffer.i

# target to preprocess a source file
src/graphics/buffers/lotus_indexbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_indexbuffer.cpp.i
.PHONY : src/graphics/buffers/lotus_indexbuffer.cpp.i

src/graphics/buffers/lotus_indexbuffer.s: src/graphics/buffers/lotus_indexbuffer.cpp.s
.PHONY : src/graphics/buffers/lotus_indexbuffer.s

# target to generate assembly for a file
src/graphics/buffers/lotus_indexbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_indexbuffer.cpp.s
.PHONY : src/graphics/buffers/lotus_indexbuffer.cpp.s

src/graphics/buffers/lotus_vertexarray.o: src/graphics/buffers/lotus_vertexarray.cpp.o
.PHONY : src/graphics/buffers/lotus_vertexarray.o

# target to build an object file
src/graphics/buffers/lotus_vertexarray.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_vertexarray.cpp.o
.PHONY : src/graphics/buffers/lotus_vertexarray.cpp.o

src/graphics/buffers/lotus_vertexarray.i: src/graphics/buffers/lotus_vertexarray.cpp.i
.PHONY : src/graphics/buffers/lotus_vertexarray.i

# target to preprocess a source file
src/graphics/buffers/lotus_vertexarray.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_vertexarray.cpp.i
.PHONY : src/graphics/buffers/lotus_vertexarray.cpp.i

src/graphics/buffers/lotus_vertexarray.s: src/graphics/buffers/lotus_vertexarray.cpp.s
.PHONY : src/graphics/buffers/lotus_vertexarray.s

# target to generate assembly for a file
src/graphics/buffers/lotus_vertexarray.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/buffers/lotus_vertexarray.cpp.s
.PHONY : src/graphics/buffers/lotus_vertexarray.cpp.s

src/graphics/lotus_shader.o: src/graphics/lotus_shader.cpp.o
.PHONY : src/graphics/lotus_shader.o

# target to build an object file
src/graphics/lotus_shader.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_shader.cpp.o
.PHONY : src/graphics/lotus_shader.cpp.o

src/graphics/lotus_shader.i: src/graphics/lotus_shader.cpp.i
.PHONY : src/graphics/lotus_shader.i

# target to preprocess a source file
src/graphics/lotus_shader.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_shader.cpp.i
.PHONY : src/graphics/lotus_shader.cpp.i

src/graphics/lotus_shader.s: src/graphics/lotus_shader.cpp.s
.PHONY : src/graphics/lotus_shader.s

# target to generate assembly for a file
src/graphics/lotus_shader.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_shader.cpp.s
.PHONY : src/graphics/lotus_shader.cpp.s

src/graphics/lotus_window.o: src/graphics/lotus_window.cpp.o
.PHONY : src/graphics/lotus_window.o

# target to build an object file
src/graphics/lotus_window.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_window.cpp.o
.PHONY : src/graphics/lotus_window.cpp.o

src/graphics/lotus_window.i: src/graphics/lotus_window.cpp.i
.PHONY : src/graphics/lotus_window.i

# target to preprocess a source file
src/graphics/lotus_window.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_window.cpp.i
.PHONY : src/graphics/lotus_window.cpp.i

src/graphics/lotus_window.s: src/graphics/lotus_window.cpp.s
.PHONY : src/graphics/lotus_window.s

# target to generate assembly for a file
src/graphics/lotus_window.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/lotus_window.cpp.s
.PHONY : src/graphics/lotus_window.cpp.s

src/graphics/renderables/lotus_renderable.o: src/graphics/renderables/lotus_renderable.cpp.o
.PHONY : src/graphics/renderables/lotus_renderable.o

# target to build an object file
src/graphics/renderables/lotus_renderable.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable.cpp.o
.PHONY : src/graphics/renderables/lotus_renderable.cpp.o

src/graphics/renderables/lotus_renderable.i: src/graphics/renderables/lotus_renderable.cpp.i
.PHONY : src/graphics/renderables/lotus_renderable.i

# target to preprocess a source file
src/graphics/renderables/lotus_renderable.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable.cpp.i
.PHONY : src/graphics/renderables/lotus_renderable.cpp.i

src/graphics/renderables/lotus_renderable.s: src/graphics/renderables/lotus_renderable.cpp.s
.PHONY : src/graphics/renderables/lotus_renderable.s

# target to generate assembly for a file
src/graphics/renderables/lotus_renderable.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable.cpp.s
.PHONY : src/graphics/renderables/lotus_renderable.cpp.s

src/graphics/renderables/lotus_renderable2d.o: src/graphics/renderables/lotus_renderable2d.cpp.o
.PHONY : src/graphics/renderables/lotus_renderable2d.o

# target to build an object file
src/graphics/renderables/lotus_renderable2d.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable2d.cpp.o
.PHONY : src/graphics/renderables/lotus_renderable2d.cpp.o

src/graphics/renderables/lotus_renderable2d.i: src/graphics/renderables/lotus_renderable2d.cpp.i
.PHONY : src/graphics/renderables/lotus_renderable2d.i

# target to preprocess a source file
src/graphics/renderables/lotus_renderable2d.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable2d.cpp.i
.PHONY : src/graphics/renderables/lotus_renderable2d.cpp.i

src/graphics/renderables/lotus_renderable2d.s: src/graphics/renderables/lotus_renderable2d.cpp.s
.PHONY : src/graphics/renderables/lotus_renderable2d.s

# target to generate assembly for a file
src/graphics/renderables/lotus_renderable2d.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderables/lotus_renderable2d.cpp.s
.PHONY : src/graphics/renderables/lotus_renderable2d.cpp.s

src/graphics/renderers/lotus_simplerenderer.o: src/graphics/renderers/lotus_simplerenderer.cpp.o
.PHONY : src/graphics/renderers/lotus_simplerenderer.o

# target to build an object file
src/graphics/renderers/lotus_simplerenderer.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderers/lotus_simplerenderer.cpp.o
.PHONY : src/graphics/renderers/lotus_simplerenderer.cpp.o

src/graphics/renderers/lotus_simplerenderer.i: src/graphics/renderers/lotus_simplerenderer.cpp.i
.PHONY : src/graphics/renderers/lotus_simplerenderer.i

# target to preprocess a source file
src/graphics/renderers/lotus_simplerenderer.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderers/lotus_simplerenderer.cpp.i
.PHONY : src/graphics/renderers/lotus_simplerenderer.cpp.i

src/graphics/renderers/lotus_simplerenderer.s: src/graphics/renderers/lotus_simplerenderer.cpp.s
.PHONY : src/graphics/renderers/lotus_simplerenderer.s

# target to generate assembly for a file
src/graphics/renderers/lotus_simplerenderer.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/graphics/renderers/lotus_simplerenderer.cpp.s
.PHONY : src/graphics/renderers/lotus_simplerenderer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/maths/lotus_mat4.o: src/maths/lotus_mat4.cpp.o
.PHONY : src/maths/lotus_mat4.o

# target to build an object file
src/maths/lotus_mat4.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_mat4.cpp.o
.PHONY : src/maths/lotus_mat4.cpp.o

src/maths/lotus_mat4.i: src/maths/lotus_mat4.cpp.i
.PHONY : src/maths/lotus_mat4.i

# target to preprocess a source file
src/maths/lotus_mat4.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_mat4.cpp.i
.PHONY : src/maths/lotus_mat4.cpp.i

src/maths/lotus_mat4.s: src/maths/lotus_mat4.cpp.s
.PHONY : src/maths/lotus_mat4.s

# target to generate assembly for a file
src/maths/lotus_mat4.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_mat4.cpp.s
.PHONY : src/maths/lotus_mat4.cpp.s

src/maths/lotus_quat.o: src/maths/lotus_quat.cpp.o
.PHONY : src/maths/lotus_quat.o

# target to build an object file
src/maths/lotus_quat.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_quat.cpp.o
.PHONY : src/maths/lotus_quat.cpp.o

src/maths/lotus_quat.i: src/maths/lotus_quat.cpp.i
.PHONY : src/maths/lotus_quat.i

# target to preprocess a source file
src/maths/lotus_quat.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_quat.cpp.i
.PHONY : src/maths/lotus_quat.cpp.i

src/maths/lotus_quat.s: src/maths/lotus_quat.cpp.s
.PHONY : src/maths/lotus_quat.s

# target to generate assembly for a file
src/maths/lotus_quat.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_quat.cpp.s
.PHONY : src/maths/lotus_quat.cpp.s

src/maths/lotus_vec2.o: src/maths/lotus_vec2.cpp.o
.PHONY : src/maths/lotus_vec2.o

# target to build an object file
src/maths/lotus_vec2.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec2.cpp.o
.PHONY : src/maths/lotus_vec2.cpp.o

src/maths/lotus_vec2.i: src/maths/lotus_vec2.cpp.i
.PHONY : src/maths/lotus_vec2.i

# target to preprocess a source file
src/maths/lotus_vec2.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec2.cpp.i
.PHONY : src/maths/lotus_vec2.cpp.i

src/maths/lotus_vec2.s: src/maths/lotus_vec2.cpp.s
.PHONY : src/maths/lotus_vec2.s

# target to generate assembly for a file
src/maths/lotus_vec2.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec2.cpp.s
.PHONY : src/maths/lotus_vec2.cpp.s

src/maths/lotus_vec3.o: src/maths/lotus_vec3.cpp.o
.PHONY : src/maths/lotus_vec3.o

# target to build an object file
src/maths/lotus_vec3.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec3.cpp.o
.PHONY : src/maths/lotus_vec3.cpp.o

src/maths/lotus_vec3.i: src/maths/lotus_vec3.cpp.i
.PHONY : src/maths/lotus_vec3.i

# target to preprocess a source file
src/maths/lotus_vec3.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec3.cpp.i
.PHONY : src/maths/lotus_vec3.cpp.i

src/maths/lotus_vec3.s: src/maths/lotus_vec3.cpp.s
.PHONY : src/maths/lotus_vec3.s

# target to generate assembly for a file
src/maths/lotus_vec3.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec3.cpp.s
.PHONY : src/maths/lotus_vec3.cpp.s

src/maths/lotus_vec4.o: src/maths/lotus_vec4.cpp.o
.PHONY : src/maths/lotus_vec4.o

# target to build an object file
src/maths/lotus_vec4.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec4.cpp.o
.PHONY : src/maths/lotus_vec4.cpp.o

src/maths/lotus_vec4.i: src/maths/lotus_vec4.cpp.i
.PHONY : src/maths/lotus_vec4.i

# target to preprocess a source file
src/maths/lotus_vec4.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec4.cpp.i
.PHONY : src/maths/lotus_vec4.cpp.i

src/maths/lotus_vec4.s: src/maths/lotus_vec4.cpp.s
.PHONY : src/maths/lotus_vec4.s

# target to generate assembly for a file
src/maths/lotus_vec4.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/maths/lotus_vec4.cpp.s
.PHONY : src/maths/lotus_vec4.cpp.s

src/utils/lotus_fileutils.o: src/utils/lotus_fileutils.cpp.o
.PHONY : src/utils/lotus_fileutils.o

# target to build an object file
src/utils/lotus_fileutils.cpp.o:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/utils/lotus_fileutils.cpp.o
.PHONY : src/utils/lotus_fileutils.cpp.o

src/utils/lotus_fileutils.i: src/utils/lotus_fileutils.cpp.i
.PHONY : src/utils/lotus_fileutils.i

# target to preprocess a source file
src/utils/lotus_fileutils.cpp.i:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/utils/lotus_fileutils.cpp.i
.PHONY : src/utils/lotus_fileutils.cpp.i

src/utils/lotus_fileutils.s: src/utils/lotus_fileutils.cpp.s
.PHONY : src/utils/lotus_fileutils.s

# target to generate assembly for a file
src/utils/lotus_fileutils.cpp.s:
	$(MAKE) -f CMakeFiles/Lotus.dir/build.make CMakeFiles/Lotus.dir/src/utils/lotus_fileutils.cpp.s
.PHONY : src/utils/lotus_fileutils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Lotus"
	@echo "... src/graphics/buffers/lotus_buffer.o"
	@echo "... src/graphics/buffers/lotus_buffer.i"
	@echo "... src/graphics/buffers/lotus_buffer.s"
	@echo "... src/graphics/buffers/lotus_indexbuffer.o"
	@echo "... src/graphics/buffers/lotus_indexbuffer.i"
	@echo "... src/graphics/buffers/lotus_indexbuffer.s"
	@echo "... src/graphics/buffers/lotus_vertexarray.o"
	@echo "... src/graphics/buffers/lotus_vertexarray.i"
	@echo "... src/graphics/buffers/lotus_vertexarray.s"
	@echo "... src/graphics/lotus_shader.o"
	@echo "... src/graphics/lotus_shader.i"
	@echo "... src/graphics/lotus_shader.s"
	@echo "... src/graphics/lotus_window.o"
	@echo "... src/graphics/lotus_window.i"
	@echo "... src/graphics/lotus_window.s"
	@echo "... src/graphics/renderables/lotus_renderable.o"
	@echo "... src/graphics/renderables/lotus_renderable.i"
	@echo "... src/graphics/renderables/lotus_renderable.s"
	@echo "... src/graphics/renderables/lotus_renderable2d.o"
	@echo "... src/graphics/renderables/lotus_renderable2d.i"
	@echo "... src/graphics/renderables/lotus_renderable2d.s"
	@echo "... src/graphics/renderers/lotus_simplerenderer.o"
	@echo "... src/graphics/renderers/lotus_simplerenderer.i"
	@echo "... src/graphics/renderers/lotus_simplerenderer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/maths/lotus_mat4.o"
	@echo "... src/maths/lotus_mat4.i"
	@echo "... src/maths/lotus_mat4.s"
	@echo "... src/maths/lotus_quat.o"
	@echo "... src/maths/lotus_quat.i"
	@echo "... src/maths/lotus_quat.s"
	@echo "... src/maths/lotus_vec2.o"
	@echo "... src/maths/lotus_vec2.i"
	@echo "... src/maths/lotus_vec2.s"
	@echo "... src/maths/lotus_vec3.o"
	@echo "... src/maths/lotus_vec3.i"
	@echo "... src/maths/lotus_vec3.s"
	@echo "... src/maths/lotus_vec4.o"
	@echo "... src/maths/lotus_vec4.i"
	@echo "... src/maths/lotus_vec4.s"
	@echo "... src/utils/lotus_fileutils.o"
	@echo "... src/utils/lotus_fileutils.i"
	@echo "... src/utils/lotus_fileutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

